namespace DiskScope.Models;

public enum PhotoshopItemType
{
    UserDocument,       // .psd, .psb (Active artwork/projects - do not delete casually)
    ScratchAndTemp,     // Photoshop Temp, scratch files (temporary - reclaimable)
    AdobeCache,         // CameraRaw, Media Cache (reclaimable cache)
    PresetOrAsset       // .abr, .asl, .atn, .pat, .grd (presets)
}

public class PhotoshopItem
{
    public FileRecord File { get; set; } = new();
    public PhotoshopItemType ItemType { get; set; }

    public string TypeLabel => ItemType switch
    {
        PhotoshopItemType.UserDocument => "User Document",
        PhotoshopItemType.ScratchAndTemp => "Scratch / Temp",
        PhotoshopItemType.AdobeCache => "Adobe Cache",
        PhotoshopItemType.PresetOrAsset => "Preset / Asset",
        _ => "Photoshop"
    };

    public bool IsReclaimable => ItemType == PhotoshopItemType.ScratchAndTemp || ItemType == PhotoshopItemType.AdobeCache;

    public string SafetyDescription => ItemType switch
    {
        PhotoshopItemType.UserDocument => "User creative artwork document (.PSD / .PSB). Keep safe — do not delete unless you no longer need this artwork.",
        PhotoshopItemType.ScratchAndTemp => "Temporary scratch workspace generated by Photoshop. Safe to remove if Photoshop is closed.",
        PhotoshopItemType.AdobeCache => "Camera Raw or media cache. Can be safely reclaimed to recover space; Adobe will rebuild if needed.",
        PhotoshopItemType.PresetOrAsset => "Brush (.abr), style (.asl), action (.atn), or preset pattern.",
        _ => "Photoshop storage asset."
    };
}
